development:
  clients:
    default:
      database: cines-api
      hosts:
        - localhost:27017
        
production:
  clients:
    default:
      database: cines-api
      hosts:
        - localhost:27017